import os
import subprocess
import sys
import gzip

DASHBOARD_DIR = "dashboard"
DIST_HTML = os.path.join(DASHBOARD_DIR, "dist", "index.html")
OUT_DIR = os.path.join("src", "network", "html")
OUT_HEADER = os.path.join(OUT_DIR, "DashboardHtml.generated.h")

def build_dashboard():
    print("Building React dashboard...")
    result = subprocess.run(
        ["npm", "run", "build"],
        cwd=DASHBOARD_DIR,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print(result.stdout)
        print(result.stderr, file=sys.stderr)
        sys.exit(1)
    print(result.stdout.strip())

def generate_header(html_path: str, out_path: str):
    with open(html_path, "r", encoding="utf-8") as f:
        content = f.read()

    compressed = gzip.compress(content.encode("utf-8"), compresslevel=9)

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n")
        h.write("#include <cstddef>\n\n")
        h.write("constexpr char DashboardHtml[] PROGMEM = {\n")
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i + 16]
            h.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
        h.write("};\n\n")
        h.write(f"constexpr size_t DashboardHtmlCompressedSize = {len(compressed)};\n")
        h.write(f"constexpr size_t DashboardHtmlOriginalSize = {len(content.encode('utf-8'))};\n")

    print(f"Generated: {out_path}")
    print(f"  Original:   {len(content):>8} bytes")
    print(f"  Compressed: {len(compressed):>8} bytes ({100*len(compressed)/len(content):.1f}%)")

build_dashboard()
generate_header(DIST_HTML, OUT_HEADER)
