"""
Generates 1-bit icon headers and Icons.h registry from SVG sources.

Each icon in ICONS defines:
  name  — SVG filename stem (src/components/icons/src/{name}.svg)
  enum  — UIIcon enum value (must match MyneUI.h)
  sizes — pixel sizes to generate

Output:
  src/components/icons/{name}{size}.h   — 1-bit bitmap arrays
  src/components/icons/Icons.h          — includes + iconForName() function

Usage:
  python scripts/build_icons.py
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SVG_DIR = os.path.join(ROOT, 'src', 'components', 'icons', 'src')
OUT_DIR = os.path.join(ROOT, 'src', 'components', 'icons')

sys.path.insert(0, os.path.join(ROOT, 'scripts'))
from convert_icon import load_image, image_to_c_array

# ──────────────────────────────────────────────────────────────
# Icon config — must stay in sync with UIIcon enum (MyneUI.h)
# ──────────────────────────────────────────────────────────────
ICONS = [
    {'name': 'folder',         'enum': 'FolderIcon',         'sizes': [24, 64]},
    {'name': 'image',          'enum': 'ImageIcon',          'sizes': [24]},
    {'name': 'file',           'enum': 'FileIcon',           'sizes': [24]},
    {'name': 'book',           'enum': 'BookIcon',           'sizes': [24, 32, 64]},
    {'name': 'bookMarked',     'enum': 'BookMarkedIcon',     'sizes': [24, 32, 64]},
    {'name': 'libraryBig',     'enum': 'LibraryBigIcon',     'sizes': [24, 64]},
    {'name': 'folderBookmark', 'enum': 'FolderBookmarkIcon', 'sizes': [24, 32]},
    {'name': 'network',       'enum': 'NetworkIcon',       'sizes': [64]},
    {'name': 'settings',       'enum': 'SettingsIcon',       'sizes': [64]},
    {'name': 'wifi',           'enum': 'WifiIcon',           'sizes': [32]},
    {'name': 'hotspot',        'enum': 'HotspotIcon',        'sizes': [32]},
    {'name': 'bookHeart',        'enum': 'BookHeartIcon',        'sizes': [64]},
      {'name': 'chart',        'enum': 'ChartIcon',        'sizes': [64]},
    {'name': 'chevronRight',   'enum': 'ChevronRightIcon',   'sizes': [24]},
]


def to_pascal(s: str) -> str:
    return s[0].upper() + s[1:] if s else s


def build_variant(name: str, size: int) -> None:
    svg = os.path.join(SVG_DIR, f'{name}.svg')
    array_name = f'{to_pascal(name)}{size}Icon'
    img = load_image(svg, size, size)
    c = image_to_c_array(img, array_name)
    out = os.path.join(OUT_DIR, f'{name}{size}.h')
    with open(out, 'w') as f:
        f.write(c)
    print(f'  {name}.svg ({size}×{size}) → {os.path.relpath(out, ROOT)}')


def generate_registry() -> str:
    enum_values = ', '.join(ic['enum'] for ic in ICONS)

    lines = [
        '#pragma once',
        '// Auto-generated by scripts/build_icons.py — do not edit.',
        '',
        '#include <cstdint>',
        '',
        f'enum UIIcon {{ {enum_values} }};',
        '',
    ]

    for icon in ICONS:
        for size in icon['sizes']:
            lines.append(f'#include "{icon["name"]}{size}.h"')

    lines += [
        '',
        'inline const uint8_t* iconForName(UIIcon icon, int size) {',
        '  switch (size) {',
    ]

    by_size: dict[int, list] = {}
    for icon in ICONS:
        for size in icon['sizes']:
            by_size.setdefault(size, []).append(icon)

    for size in sorted(by_size):
        lines.append(f'    case {size}: switch (icon) {{')
        for icon in by_size[size]:
            arr = f'{to_pascal(icon["name"])}{size}Icon'
            lines.append(f'      case UIIcon::{icon["enum"]}: return {arr};')
        lines += ['      default: return nullptr;', '    }']

    lines += ['    default: return nullptr;', '  }', '}', '']
    return '\n'.join(lines)


def main():
    os.makedirs(OUT_DIR, exist_ok=True)

    total = sum(len(ic['sizes']) for ic in ICONS)
    print(f'Building {total} icon variant(s)...')

    errors = []
    for icon in ICONS:
        for size in icon['sizes']:
            try:
                build_variant(icon['name'], size)
            except Exception as e:
                errors.append(e)
                print(f'  ERROR {icon["name"]}@{size}: {e}')

    registry_path = os.path.join(OUT_DIR, 'Icons.h')
    with open(registry_path, 'w') as f:
        f.write(generate_registry())
    print(f'  → {os.path.relpath(registry_path, ROOT)}')

    if errors:
        sys.exit(1)
    print('Done.')


if __name__ == '__main__':
    main()
