#pragma once
// Auto-generated by scripts/build_icons.py — do not edit.

#include <cstdint>

enum UIIcon {
  FolderIcon,
  ImageIcon,
  FileIcon,
  BookIcon,
  BookMarkedIcon,
  LibraryBigIcon,
  FolderBookmarkIcon,
  NetworkIcon,
  SettingsIcon,
  WifiIcon,
  HotspotIcon,
  BookHeartIcon,
  ChartIcon,
  ChevronRightIcon
};

#include "book24.h"
#include "book32.h"
#include "book64.h"
#include "bookHeart64.h"
#include "bookMarked24.h"
#include "bookMarked32.h"
#include "bookMarked64.h"
#include "chart64.h"
#include "chevronRight24.h"
#include "file24.h"
#include "folder24.h"
#include "folder64.h"
#include "folderBookmark24.h"
#include "folderBookmark32.h"
#include "hotspot32.h"
#include "image24.h"
#include "libraryBig24.h"
#include "libraryBig64.h"
#include "network64.h"
#include "settings64.h"
#include "wifi32.h"

inline const uint8_t* iconForName(UIIcon icon, int size) {
  switch (size) {
    case 24:
      switch (icon) {
        case UIIcon::FolderIcon:
          return Folder24Icon;
        case UIIcon::ImageIcon:
          return Image24Icon;
        case UIIcon::FileIcon:
          return File24Icon;
        case UIIcon::BookIcon:
          return Book24Icon;
        case UIIcon::BookMarkedIcon:
          return BookMarked24Icon;
        case UIIcon::LibraryBigIcon:
          return LibraryBig24Icon;
        case UIIcon::FolderBookmarkIcon:
          return FolderBookmark24Icon;
        case UIIcon::ChevronRightIcon:
          return ChevronRight24Icon;
        default:
          return nullptr;
      }
    case 32:
      switch (icon) {
        case UIIcon::BookIcon:
          return Book32Icon;
        case UIIcon::BookMarkedIcon:
          return BookMarked32Icon;
        case UIIcon::FolderBookmarkIcon:
          return FolderBookmark32Icon;
        case UIIcon::WifiIcon:
          return Wifi32Icon;
        case UIIcon::HotspotIcon:
          return Hotspot32Icon;
        default:
          return nullptr;
      }
    case 64:
      switch (icon) {
        case UIIcon::FolderIcon:
          return Folder64Icon;
        case UIIcon::BookIcon:
          return Book64Icon;
        case UIIcon::BookMarkedIcon:
          return BookMarked64Icon;
        case UIIcon::LibraryBigIcon:
          return LibraryBig64Icon;
        case UIIcon::NetworkIcon:
          return Network64Icon;
        case UIIcon::SettingsIcon:
          return Settings64Icon;
        case UIIcon::BookHeartIcon:
          return BookHeart64Icon;
        case UIIcon::ChartIcon:
          return Chart64Icon;
        default:
          return nullptr;
      }
    default:
      return nullptr;
  }
}
